apiVersion: v1
kind: Pod
metadata:
  name: myapp-docker-default-2
  labels:
    name: myapp-docker-default-2
    lazykubetest: e2e-test
spec:
  containers:
  - name: main
    image: library/mysql:5.6
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"