apiVersion: v1
kind: Pod
metadata:
  name: myapp-docker-default
  labels:
    name: myapp-docker-default
    lazykubetest: e2e-test
spec:
  containers:
  - name: main
    image: mysql:5.6
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"