apiVersion: v1
kind: Pod
metadata:
  name: myapp-docker
  labels:
    name: myapp-docker
    lazykubetest: e2e-test
spec:
  containers:
  - name: main
    image: docker.io/library/mysql:5.6
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
