apiVersion: v1
kind: ConfigMap
metadata:
  name: lazykube-config
  namespace: kube-system
data: 
  config: |
    replaceStrategies:
      - case: "quay.io"
        mode: prefix
        value: "quay.azk8s.cn"
      - case: "gcr.io"
        mode: prefix
        value: "gcr.azk8s.cn"
      - case: "k8s.gcr.io"
        mode: prefix
        value: "gcr.azk8s.cn/google-containers"
      - case: "docker.io"
        mode: prefix
        value: "test.azk8s.cn"
      - case: "default"
        mode: default
        value: "test.azk8s.cn"