apiVersion: v1
kind: Pod
metadata:
  name: myapp-quay
  labels:
    name: myapp-quay
    lazykubetest: e2e-test
spec:
  initContainers:
    - name: init
      image: quay.io/dexidp/dex:v2.10.0
      imagePullPolicy: Always
  containers:
  - name: main
    image: quay.io/dexidp/dex:v2.10.0
    imagePullPolicy: Always
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
