apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: lazykube-webhook-cfg
  labels:
    app: lazykube
webhooks:
  - name: lazykube.myway5.com
    clientConfig:
      service:
        name: lazykube-webhook-svc
        namespace: default
        path: "/mutate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1ekNDQWMrZ0F3SUJBZ0lCQVRBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwdGFXNXAKYTNWaVpVTkJNQjRYRFRFNU1URXlNREF3TWpnek4xb1hEVEk1TVRFeE9EQXdNamd6TjFvd0ZURVRNQkVHQTFVRQpBeE1LYldsdWFXdDFZbVZEUVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnUxCmRpd1loeisvSUVsd1lCSEo2eG1jaFRpS29SQTZUYnJWNjRwSCtpaXhZZkVITjVSZlhxWU44YXBPbGNlbU1CbzIKL2NuamRxZ3Q1eFdLTFdneVhKTHd6Tkl2QndybUZubi9uUXJxSXhDeTZMUlJtWjJvV1d4TEdjREg5UTdNdUZONgpJd2c5THBLQytQWjlMQ0p3Q3FuVVZiTDUyMHhwT3RvMEhEMU8rVE1IdFJKYlRnWFArcit2VklIWW9RdE42Nnl5CkNnYlRrSmxsVzNQMUoxazN2dXJOVzRhdHhRczF0S1VKZUhBS1hyWXR2T25EcWZpYzE0aktrYlo0NHdTMXczeDQKQVlTVktHTFl1YmlZQlVyRVZUUHRxTms1SlVTNzJjMjFNSUM2cEM3a0RNWnZDay9jMGlXY29CTEpZRmJzbi95NAplUWFoMnFEaVFSQnBIcHRzeXFFQ0F3RUFBYU5DTUVBd0RnWURWUjBQQVFIL0JBUURBZ0trTUIwR0ExVWRKUVFXCk1CUUdDQ3NHQVFVRkJ3TUNCZ2dyQmdFRkJRY0RBVEFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxR1NJYjMKRFFFQkN3VUFBNElCQVFBUjRoaFJRZ2YvNXVEU1pBZWl4MjhOckppL0d6b05lV01mN0xzK3lzcHZraXYrMWZwOApkMlpkaEhLZXdwaUxWRUE3NUdXS3ZaWlM0ZzhESTFpYXZKU3VQSFNGa1hlVHJkUVdlazQrVEU1TTMzbmdqNmZnCmdtLytTSkVpbzhJMjJETm95OVRldFFNclZEVlRvRWtpVDlkdzhSSmluUTRJZTBMRnpUSE96aXRsZGpNNVdCcnIKQjlwNzBaWXJtQmk0WDIxV3hDTUNaVDA2NnF3S0pyd0dSSWRRWnUvbjcrdGs2RStUWDkrRnZBT1BRc2U2QUJUSwpCQnBXVnRiSXpSeTUyd2tCb0l0UkN6cks2QVpTTXdTUGVLcnJvVE9kRmFOZEN2WGhEdUxPZ2JaMHFzT3VCTDI4CmZQZ2lyeXlrVitWSGsrNzQ3L2gra1hFSTB2SFpPUlAwYU5LbAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    # namespaceSelector:
    #   matchLabels:
    #     sidecar-injector: enabled
